name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        shared: [ON, OFF]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure mini-sql
        run: >
          cmake -S . -B build
          -DBUILD_SHARED_LIBS=${{ matrix.shared }}
          -DCMAKE_INSTALL_PREFIX=install
          -DCMAKE_BUILD_TYPE=Release

      - name: Build mini-sql
        run: cmake --build build --config Release

      - name: Install mini-sql
        run: cmake --install build --config Release

      - name: Configure consumer
        run: >
          cmake -S consumer -B consumer/build
          -DCMAKE_PREFIX_PATH=${{ github.workspace}}/install
          -DCMAKE_BUILD_TYPE=Release

      - name: Build consumer
        run: cmake --build consumer/build  --config Release

      - name: Copy mini-sql dll on Windows shared build
        if: ${{ (matrix.os == 'windows-latest') && (matrix.shared == 'ON') }}
        run: copy install/bin/minisql.dll consumer/build/Release/minisql.dll

      - name: Run consumer
        shell: bash
        run: |
          if [ "${{ matrix.os}}" = "windows-latest"]; then
            ./consumer/build/Release/consumer
          else
            ./consumer/build/consumer
          fi

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure mini-sql
        run: cmake -S . -B build -DBUILD_TESTS=ON

      - name: Build mini-sql
        run: cmake --build build

      - name: Run integration tests
        run: ./build/tests/integration/runner